/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vues;

import Entity.Famille;
import Entity.FonctionsMetier;
import javax.swing.JOptionPane;
import Entity.ConnexionBdd;
import java.util.Map;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;


public class frmDashboard extends javax.swing.JFrame {

    
     FonctionsMetier fm;

    
    public frmDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        BtnGraphe1 = new javax.swing.JButton();
        BtnGraph2 = new javax.swing.JButton();
        BtnGraph3 = new javax.swing.JButton();
        Btngraph4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(89, 136, 255));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ASSET/chrome_ZpF0AWG32d.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        BtnGraphe1.setText("Nombre Medicament par Famille");
        BtnGraphe1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnGraphe1MouseClicked(evt);
            }
        });

        BtnGraph2.setText("le nombre medicament prescrit");
        BtnGraph2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnGraph2MouseClicked(evt);
            }
        });
        BtnGraph2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGraph2ActionPerformed(evt);
            }
        });

        BtnGraph3.setText("Le nombre de prescription par famille");
        BtnGraph3.setToolTipText("");
        BtnGraph3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnGraph3MouseClicked(evt);
            }
        });
        BtnGraph3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGraph3ActionPerformed(evt);
            }
        });

        Btngraph4.setText("Le nombre de interagis par medicament");
        Btngraph4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btngraph4MouseClicked(evt);
            }
        });
        Btngraph4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btngraph4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Btngraph4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnGraphe1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnGraph2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnGraph3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(57, 258, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(BtnGraphe1)
                .addGap(51, 51, 51)
                .addComponent(BtnGraph2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(BtnGraph3)
                .addGap(39, 39, 39)
                .addComponent(Btngraph4)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        frmMain frm = new frmMain();
        frm.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        ConnexionBdd cnx = new ConnexionBdd();
        fm = new FonctionsMetier();
//        for (Famille f : fm.getAllFamille()) {
//            cmbFam.addItem(f.getFamLibelle());
//        }
    }//GEN-LAST:event_formWindowOpened

    private void BtnGraph2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGraph2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGraph2ActionPerformed

    private void BtnGraphe1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGraphe1MouseClicked
        DefaultCategoryDataset donnees = new DefaultCategoryDataset();
        // Permet de remplir un jeu de séries dans notre objet donnees
        // DatasSet
        
        for(Map.Entry valeur : fm.GetDatasGraph1().entrySet())
        {
            donnees.setValue(Double.parseDouble(valeur.getValue().toString()),"nombre médicament",valeur.getKey().toString());
        }
        JFreeChart graph = ChartFactory.createBarChart("Nombre médicament par famille","","nombre médicament",donnees,PlotOrientation.VERTICAL,false, true, false);
        ChartFrame fra = new ChartFrame("Graphique n°1", graph);
        fra.pack();
        fra.setVisible(true);
    }//GEN-LAST:event_BtnGraphe1MouseClicked

    private void BtnGraph2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGraph2MouseClicked
        DefaultPieDataset donnees = new DefaultPieDataset();
        // Permet de remplir un jeu de séries dans notre objet donnees
        // DatasSet
        for(Map.Entry valeur : fm.GetDatasGraph2().entrySet())
        {
            donnees.setValue(valeur.getKey().toString(),Double.parseDouble(valeur.getValue().toString()));
        }
        JFreeChart graph = ChartFactory.createPieChart("le Nombre médicament prescrit",donnees,true,true,false);
        ChartFrame fra = new ChartFrame("Graphique n°2", graph);
        fra.pack();
        fra.setVisible(true);
    }//GEN-LAST:event_BtnGraph2MouseClicked

    private void Btngraph4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btngraph4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btngraph4ActionPerformed

    private void Btngraph4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btngraph4MouseClicked
        DefaultPieDataset donnees = new DefaultPieDataset();
        // Permet de remplir un jeu de séries dans notre objet donnees
        // DatasSet
        for(Map.Entry valeur : fm.GetDatasGraph4().entrySet())
        {
            donnees.setValue(valeur.getKey().toString(),Double.parseDouble(valeur.getValue().toString()));
        }
        JFreeChart graph = ChartFactory.createPieChart("le Nombre interagis par famille",donnees,true,true,false);
        ChartFrame fra = new ChartFrame("Graphique n°4", graph);
        fra.pack();
        fra.setVisible(true);
    }//GEN-LAST:event_Btngraph4MouseClicked

    private void BtnGraph3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGraph3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGraph3ActionPerformed

    private void BtnGraph3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnGraph3MouseClicked

        DefaultCategoryDataset donnees = new DefaultCategoryDataset();
        // Permet de remplir un jeu de séries dans notre objet donnees
        // DatasSet
        
        for(Map.Entry valeur : fm.GetDatasGraph3().entrySet())
        {
            donnees.setValue(Double.parseDouble(valeur.getValue().toString()),"nombre médicament",valeur.getKey().toString());
        }
        JFreeChart graph = ChartFactory.createBarChart("le Nombre médicament prescrit par famille","","nombre médicament",donnees,PlotOrientation.VERTICAL,false, true, false);
        ChartFrame fra = new ChartFrame("Graphique n°3", graph);
        fra.pack();
        fra.setVisible(true);
    }//GEN-LAST:event_BtnGraph3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGraph2;
    private javax.swing.JButton BtnGraph3;
    private javax.swing.JButton BtnGraphe1;
    private javax.swing.JButton Btngraph4;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
